import { Inter } from 'next/font/google'
import './globals.css'
import { faSearch, faShoppingCart, faUser, faChevronLeft, faChevronRight } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  lang:'kr'
}

export default function RootLayout({ children }) {
  return (
    <html className="container" lang="ko">
      <body className={inter.className}>   {/* 상단 내비게이션 */}
      <div className="navigation">
        {/* 로고 이미지 */}
        <img src="/logo1.jpg" alt="로고" className="logo" />

        {/* 검색 창 */}
        <div className="searchContainer">
          <input
            type="text"
            placeholder="검색어를 입력하세요"
            className="searchInput"
          />
          <button className="searchButton">
            <FontAwesomeIcon icon={faSearch} />
            검색
          </button>
        </div>

        {/* 장바구니 및 유저 아이콘 */}
        <div className="cartUserIcons">
          <FontAwesomeIcon icon={faShoppingCart} className="cartIcon" />
          <FontAwesomeIcon icon={faUser} className="userIcon" />
        </div>
      </div>
      {children}</body>
    </html>
  )
}
